name: irhydra
dependencies:
  archive: any
  browser: any
  collection: any
  fixnum: any
  paper_elements: any
  polymer: any
  sass: any
transformers:
- sass
- polymer:
    entry_points: web/index.html
